import { ILang } from "./interface";
export const enUS: ILang = {
  cancel: "Cancel",
  clear: "Clear",
  confirm: "Confirm",
  delete: "Delete",
  enter: "Enter",
  finish: "Finish",
  friday: "Fri",
  labelIsRequired: "{label} is required",
  labelShouldBeBoolean: "{label} should be a boolean",
  labelShouldBeNumber: "{label} should be a number",
  labelShouldBeString: "{label} should be a string",
  monday: "Mon",
  noData: "No Data",
  pleaseInput: "Please input",
  pleaseInputLabel: "Please input {label}",
  pleaseSelectLabel: "Please select {label}",
  sateday: "Sat",
  submit: "Submit",
  sunday: "Sun",
  symbolEmpty: "-",
  thursday: "Thu",
  tuesday: "Tue",
  wednesday: "Wed",
  xDaysYHoursZMinutes: "{x} days {y} hours {z} mins",
  xHoursYMinutes: "{x} hours {y} mins",
  xMinutes: "{x} mins",
};
