import { ILang } from "./interface";
export const zhCN: ILang = {
  cancel: "取消",
  clear: "清除",
  confirm: "确认",
  delete: "删除",
  enter: "回车",
  finish: "完成",
  friday: "五",
  labelIsRequired: "{label} 必填",
  labelShouldBeBoolean: "{label} 应该为布尔值",
  labelShouldBeNumber: "{label} 应该为数字",
  labelShouldBeString: "{label} 应该为字符串",
  monday: "一",
  noData: "没有数据",
  pleaseInput: "请输入",
  pleaseInputLabel: "请输入{label}",
  pleaseSelectLabel: "请选择{label}",
  sateday: "六",
  submit: "提交",
  sunday: "日",
  symbolEmpty: "-",
  thursday: "四",
  tuesday: "二",
  wednesday: "三",
  xDaysYHoursZMinutes: "{x}天{y}小时{z}分钟",
  xHoursYMinutes: "{x}小时{y}分钟",
  xMinutes: "{x}分钟",
};
